// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVipCard = "vip_card"

// VipCard mapped from table <vip_card>
type VipCard struct {
	ID           uint64    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title        string    `gorm:"column:title;comment:标题" json:"title"`      // 标题
	Day          uint32    `gorm:"column:day;not null;comment:天数" json:"day"` // 天数
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
	IosProductID string    `gorm:"column:ios_product_id" json:"ios_product_id"`
	Ios          uint32    `gorm:"column:ios;not null;comment:apple" json:"ios"`                          // apple
	Android      uint32    `gorm:"column:android;not null;comment:安卓" json:"android"`                     // 安卓
	Harmony      uint32    `gorm:"column:harmony;not null;comment:鸿蒙" json:"harmony"`                     // 鸿蒙
	ListPrice    uint32    `gorm:"column:list_price;not null;comment:划线价" json:"list_price"`              // 划线价
	Kind         uint32    `gorm:"column:kind;not null;default:1;comment:1普通会员 2 联合会员 3连续订阅" json:"kind"` // 1普通会员 2 联合会员 3连续订阅
	Sort         int32     `gorm:"column:sort;not null;default:1;comment:排序" json:"sort"`                 // 排序
}

// TableName VipCard's table name
func (*VipCard) TableName() string {
	return TableNameVipCard
}
